ANA MARIA GARCIA GOMEZ

In [3]:
import numpy as np
import pandas as pd

precios = pd.Series([144, 256, 181, 472])
print(precios)
print(type(precios))

0    144
1    256
2    181
3    472
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
portafolio = pd.DataFrame({
    "ticker": ["AMZN", "NVDA", "MSFT", "V"],
    "cantidad": [17, 8, 20, 10],
    "precio": [143, 209, 212, 403]
})
print(portafolio)
print(type(portafolio))

  ticker  cantidad  precio
0   AMZN        17     143
1   NVDA         8     209
2   MSFT        20     212
3      V        10     403
<class 'pandas.core.frame.DataFrame'>

In [5]:
import numpy as np
import pandas as pd

print("pandas", pd.__version__, "listo para usar.")

pandas 2.2.3 listo para usar.

In [6]:
portafolio = pd.DataFrame({
    "ticker": ["AMZN", "NVDA", "MSFT", "V"],
    "cantidad": [17, 8, 20, 10],
    "precio_compra": [143, 209, 212, 403],
    "precio_actual": [144, 256, 181, 472]
})

portafolio

  ticker  cantidad  precio_compra  precio_actual
0   AMZN        17            143            144
1   NVDA         8            209            256
2   MSFT        20            212            181
3      V        10            403            472

In [7]:
print(portafolio.head())     # primeras filas
print(portafolio.shape)       # (filas, columnas)
print(portafolio.dtypes)       # tipo de cada columna
print(portafolio.describe())     # resumen estadístico

  ticker  cantidad  precio_compra  precio_actual
0   AMZN        17            143            144
1   NVDA         8            209            256
2   MSFT        20            212            181
3      V        10            403            472
(4, 4)
ticker           object
cantidad          int64
precio_compra     int64
precio_actual     int64
dtype: object
        cantidad  precio_compra  precio_actual
count   4.000000       4.000000       4.000000
mean   13.750000     241.750000     263.250000
std     5.678908     112.117126     146.759156
min     8.000000     143.000000     144.000000
25%     9.500000     192.500000     171.750000
50%    13.500000     210.500000     218.500000
75%    17.750000     259.750000     310.000000
max    20.000000     403.000000     472.000000

In [8]:
print(portafolio["ticker"])
print(portafolio.loc[0])

0    AMZN
1    NVDA
2    MSFT
3       V
Name: ticker, dtype: object
ticker           AMZN
cantidad           17
precio_compra     143
precio_actual     144
Name: 0, dtype: object

In [9]:
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
muchas_unidades

  ticker  cantidad  precio_compra  precio_actual
0   AMZN        17            143            144
2   MSFT        20            212            181
3      V        10            403            472

In [10]:
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())   # promedio
print(portafolio["ganancia"].std())   # desviación estándar
portafolio.sort_values(by="ganancia")

115.75
562.3085600154658

  ticker  cantidad  precio_compra  precio_actual  valor_actual  ganancia
2   MSFT        20            212            181          3620      -620
0   AMZN        17            143            144          2448        17
1   NVDA         8            209            256          2048       376
3      V        10            403            472          4720       690

In [12]:
portafolio = pd.DataFrame({
    "ticker": ["AMZN", "NVDA", "MSFT", "V"],
    "cantidad": [17, 8, 20, 10],
    "precio_compra": [143, 209, 212, 403],
    "precio_actual": [144, 256, 181, 472]
})

portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])
portafolio["rendimiento"] = (portafolio["ganancia"] / (portafolio["cantidad"] * portafolio["precio_compra"])) * 100

en_perdida = portafolio[portafolio["rendimiento"] < 0]
portafolio.sort_values(by="rendimiento", ascending=False)

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
1,NVDA,8,209,256,2048,376,22.488038
3,V,10,403,472,4720,690,17.121588
0,AMZN,17,143,144,2448,17,0.699301
2,MSFT,20,212,181,3620,-620,-14.622642

### Tu tarea

Con `mi_portafolio_dict` y `mis_precios_dict`:

1. Construye un DataFrame con las columnas `ticker`, `cantidad`, `precio_compra`, `precio_actual`.
2. Agrega las columnas `valor_actual`, `ganancia` y `rendimiento`.
3. Filtra los activos en pérdida.
4. Ordena el DataFrame de mayor a menor rendimiento.

In [21]:
import pandas as pd

# 1. Definición de diccionarios/datos basados en la imagen
mi_portafolio_dict = {
    "ticker": ["AMZN", "NVDA", "MSFT", "V"],
    "cantidad": [17, 8, 20, 10],
    "precio_compra": [143, 209, 212, 403]
}

mis_precios_dict = {
    "precio_actual": [144, 256, 181, 472]
}

df = pd.DataFrame(mi_portafolio_dict)
df["precio_actual"] = mis_precios_dict["precio_actual"]

df["valor_compra"] = df["cantidad"] * df["precio_compra"]
df["valor_actual"] = df["cantidad"] * df["precio_actual"]
df["ganancia"] = df["valor_actual"] - df["valor_compra"]
df["rendimiento"] = (df["ganancia"] / df["valor_compra"]) * 100

# 4. Filtrar los activos en pérdida (rendimiento < 0)
en_perdida = df[df["rendimiento"] < 0]

# 5. Ordenar de mayor a menor rendimiento
df_ordenado = df.sort_values(by="rendimiento", ascending=False)

# Imprimir resultados
print("--- Activos en pérdida ---")
print(en_perdida[["ticker", "cantidad", "ganancia", "rendimiento"]])

print("\n--- Portafolio ordenado por rendimiento (mayor a menor) ---")
print(df_ordenado)

--- Activos en pérdida ---
  ticker  cantidad  ganancia  rendimiento
2   MSFT        20      -620   -14.622642

--- Portafolio ordenado por rendimiento (mayor a menor) ---
  ticker  cantidad  precio_compra  precio_actual  valor_compra  valor_actual  \
1   NVDA         8            209            256          1672          2048
3      V        10            403            472          4030          4720
0   AMZN        17            143            144          2431          2448
2   MSFT        20            212            181          4240          3620

   ganancia  rendimiento
1       376    22.488038
3       690    17.121588
0        17     0.699301
2      -620   -14.622642

### Exit ticket

«Mi portafolio, ordenado de mayor a menor rendimiento, tiene a **NVDA** primero y a **MSFT** último. **1** activos están en pérdida.»

---

📚 **Fuentes** · ["10 minutes to pandas"](https://pandas.pydata.org/docs/user_guide/10min.html) · ["Package overview"](https://pandas.pydata.org/docs/getting_started/overview.html)